# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.0.1
  
jobs:
 
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
            
workflows:
  build-test-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only:
                - main          
